/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jeeex.objregex.javacc;

public
class ASTIdentifier extends com.jeeex.objregex.javacc.EnhancedNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(RegexParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.jeeex.objregex.impl.State jjtAccept(RegexParserVisitor visitor, com.jeeex.objregex.impl.SingleTransitionFactory data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5837290e4c41a92568c92792a29367c8 (do not edit this line) */
