/* Generated By:JJTree: Do not edit this line. ASTNegativeIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jeeex.objregex.javacc;

public
class ASTNegativeIdentifier extends com.jeeex.objregex.javacc.EnhancedNode {
  public ASTNegativeIdentifier(int id) {
    super(id);
  }

  public ASTNegativeIdentifier(RegexParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.jeeex.objregex.impl.State jjtAccept(RegexParserVisitor visitor, com.jeeex.objregex.impl.SingleTransitionFactory data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3008889ea074da227f510d90855c6a9e (do not edit this line) */
