/* Generated By:JJTree: Do not edit this line. ASTOperatorExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jeeex.objregex.javacc;

public
class ASTOperatorExpr extends com.jeeex.objregex.javacc.EnhancedNode {
  public ASTOperatorExpr(int id) {
    super(id);
  }

  public ASTOperatorExpr(RegexParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.jeeex.objregex.impl.State jjtAccept(RegexParserVisitor visitor, com.jeeex.objregex.impl.SingleTransitionFactory data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9879dc04fd3e85f83a0ad237028f2661 (do not edit this line) */
