/* Generated By:JJTree: Do not edit this line. ASTSpecialIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jeeex.objregex.javacc;

public
class ASTSpecialIdentifier extends com.jeeex.objregex.javacc.EnhancedNode {
  public ASTSpecialIdentifier(int id) {
    super(id);
  }

  public ASTSpecialIdentifier(RegexParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.jeeex.objregex.impl.State jjtAccept(RegexParserVisitor visitor, com.jeeex.objregex.impl.SingleTransitionFactory data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b7b2849266bee54c8bd9d2e9f797aa0c (do not edit this line) */
