/* Generated By:JJTree: Do not edit this line. ASTConcatExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jeeex.objregex.javacc;

public
class ASTConcatExpr extends com.jeeex.objregex.javacc.EnhancedNode {
  public ASTConcatExpr(int id) {
    super(id);
  }

  public ASTConcatExpr(RegexParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.jeeex.objregex.impl.State jjtAccept(RegexParserVisitor visitor, com.jeeex.objregex.impl.SingleTransitionFactory data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee5c47783464ed084378d7a4b48c2bf1 (do not edit this line) */
