/* Generated By:JavaCC: Do not edit this line. RegexParserTreeConstants.java Version 5.0 */
package com.jeeex.objregex.javacc;

public interface RegexParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTCONCATEXPR = 2;
  public int JJTOPERATOREXPR = 3;
  public int JJTOPERATOR = 4;
  public int JJTTERM = 5;
  public int JJTNEGATIVEIDENTIFIER = 6;
  public int JJTSPECIALIDENTIFIER = 7;
  public int JJTIDENTIFIER = 8;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "ConcatExpr",
    "OperatorExpr",
    "Operator",
    "Term",
    "NegativeIdentifier",
    "SpecialIdentifier",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=cc3ac84d5f8532c18fbaad2f9f6a944a (do not edit this line) */
