/* Generated By:JJTree&JavaCC: Do not edit this line. RegexParserConstants.java */
package com.jeeex.objregex.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int SPECIAL_IDENTIFIER = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int POSTFIX_OPERATOR = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"!\"",
    "<SPECIAL_IDENTIFIER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<POSTFIX_OPERATOR>",
    "\"|\"",
    "\"(\"",
    "\")\"",
  };

}
