/* Generated By:JavaCC: Do not edit this line. RegexParserVisitor.java Version 5.0 */
package com.jeeex.objregex.javacc;

public interface RegexParserVisitor
{
  public com.jeeex.objregex.impl.State visit(SimpleNode node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTStart node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTExpression node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTConcatExpr node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTOperatorExpr node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTOperator node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTTerm node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTNegativeIdentifier node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTSpecialIdentifier node, com.jeeex.objregex.impl.SingleTransitionFactory data);
  public com.jeeex.objregex.impl.State visit(ASTIdentifier node, com.jeeex.objregex.impl.SingleTransitionFactory data);
}
/* JavaCC - OriginalChecksum=80a11b34500dc4ea74030a184854f67d (do not edit this line) */
